#pragma once
#include <string>

std::string MAIN_PERSON = "MAIN_PERSON";
std::string TOWER_MAP = "TOWER_MAP"; 
std::string FOREST_MAP = "FOREST_MAP";
std::string PAUSE_MENU = "PAUSE_MENU";
std::string MOUSE_POINTER = "MOUSE_POINTER";
std::string MENU_SELECTED_POINTER = "MENU_SELECTED_POINTER";
std::string PAUSE_MENU_RESUME_ITEM = "PAUSE_MENU_BUTTON_RESUME";
std::string MENU_EXIT_ITEM = "MENU_BUTTON_EXIT";
std::string MENU_BACK_ITEM = "MENU_BUTTON_BACK";
std::string EVENT_MAP = "EVENT_MAP";
std::string EVENT_MENU = "EVENT_MENU";
std::string EVENT_NPC_SELECTED_MENU = "NPC_SELECTED_MENU_EVENT";
std::string MAIN_MENU = "MAIN_MENU";
std::string MAIN_MENU_START_ITEM = "MAIN_MENU_START";
std::string NPC_JEREMY_TYPE_ITEM = "NPC_JEREMY_TYPE";
std::string NPC_MARTHA_TYPE_ITEM = "NPC_MARTHA_TYPE";
std::string NPC_JEREMY_BLONDE = "NPC_JEREM_BLONDE";
std::string NPC_JEREMY_GREEN = "NPC_JEREMY_GREEN";
std::string NPC_JEREMY_PINK = "NPC_JEREMY_PINK";
std::string NPC_MARTHA_BLONDE = "NPC_MARTHA_BLONDE";
std::string NPC_MARTHA_GREEN = "NPC_MARTHA_GREEN";
std::string NPC_MARTHA_PINK = "NPC_MARTHA_PINK";
std::string EXIT = "EXIT";
