#ifndef SFMLPROJECT_REBUILD_STRUCT_SIDE_HPP
#define SFMLPROJECT_REBUILD_STRUCT_SIDE_HPP

namespace PROJECT::MOVE
{
	enum class Side
	{
		UP,
		DOWN,
		LEFT,
		RIGHT,
		NONE
	};
};
#endif //SFMLPROJECT_REBUILD_STRUCT_SIDE_HPP
